version: '3'
services:

    #Application (Laravel)
    app:
        image: 127.0.0.1:5000/parkii_backend_app
        build:
            context: .
            dockerfile: docker/prod/Dockerfile
        restart: always
        depends_on:
          - mysql
        tty: true
        environment:
            SERVICE_NAME: app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

    cron:
      image: 127.0.0.1:5000/parkii_backend_cron
      build:
        context: .
        dockerfile: docker/prod/cron.dockerfile
        args:
          - UID=${UID:-1001}
          - GID=${GID:-1001}
      volumes:
        - ./:/var/www

    # Redis instance
    redis:
        restart: always
        tty: true
        image: redis:alpine
        command: redis-server --appendonly yes
        ports:
            - 8002:6379
        volumes:
            - parkii-redis-master:/data

    # Certificate provider service
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw

    #Nginx Service
    webserver:
        image: nginx:alpine
        restart: always
        depends_on:
            - app
        tty: true
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/prod/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro

    #MySQL Service
    mysql:
        image: mysql:5.7.22
        command: --max_allowed_packet=32505856
        restart: always
        tty: true
        ports:
            - 33066:3306
        environment:
            MYSQL_DATABASE: parkii_prod
            MYSQL_ROOT_PASSWORD: parkii_app_prod
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql


#Volumes
volumes:
    dbdata:
        driver: local
    parkii-redis-master: {}
