version: '3'
services:

    #Application (Laravel)
    app:
        build:
            context: .
            dockerfile: docker/dev/Dockerfile
        container_name: app
        restart: unless-stopped
        depends_on:
            - mysql
        tty: true
        environment:
            SERVICE_NAME: app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/dev/xdebug/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/dev/xdebug/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - app-network

    # Redis instance
    redis:
        container_name: redis
        restart: unless-stopped
        tty: true
        image: redis:alpine
        command: redis-server --appendonly yes
        ports:
            - 8002:6379
        volumes:
            - parkii-redis-master:/data
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        depends_on:
            - app
        tty: true
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/dev/nginx/conf.d/:/etc/nginx/conf.d/:ro
        networks:
            - app-network

    #MySQL Service
    mysql:
        image: mysql:5.7.22
        command: --max_allowed_packet=32505856
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 33066:3306
        environment:
            MYSQL_DATABASE: parkii
            MYSQL_ROOT_PASSWORD: parkii_app
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
    parkii-redis-master: {}
