name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy Parkii API to Digital Ocean droplet
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP of server
          key: ${{secrets.SSH_KEY}} # SSH KEY
          username: ${{secrets.SSH_USER}} # USERNAME

          script: |
            cd parkii_backend/ && sh deploy.sh
            echo 'Deployment Successful'

