name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: ./vendor/bin/phpstan analyse

      - name: Build the image
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP of server
          key: ${{secrets.SSH_KEY}} # SSH KEY
          username: ${{secrets.SSH_USER}} # USERNAME
          script: |
            cd parkii_backend/ && sh build.sh
            echo 'Build APP image'

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy Parkii API to Digital Ocean droplet
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP of server
          key: ${{secrets.SSH_KEY}} # SSH KEY
          username: ${{secrets.SSH_USER}} # USERNAME
          script: |
            cd parkii_backend/ && sh deploy.sh
            echo 'Deployed app to Production'
  Test:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Check if API is runnning
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://api.parkii.dk/
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          retry-all: false # Optional, defaults to "false"
